In [17]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X).detach().numpy()

array([[-0.31959143],
       [-0.32985747]], dtype=float32)

In [18]:
# get parameter in net
print(net[0])
print(net.state_dict())

Linear(in_features=4, out_features=8, bias=True)
OrderedDict([('0.weight', tensor([[ 0.0203,  0.1810,  0.3190, -0.2308],
        [-0.3013, -0.0021,  0.4151, -0.3220],
        [ 0.0961,  0.1712,  0.4659, -0.3329],
        [-0.0903,  0.1003, -0.3421, -0.3192],
        [-0.0271, -0.3197, -0.1982, -0.4687],
        [ 0.1530,  0.4116, -0.0981,  0.1409],
        [-0.2566,  0.3544,  0.0208,  0.0007],
        [-0.2225, -0.0326, -0.4258, -0.1919]])), ('0.bias', tensor([-0.4461,  0.3284, -0.0607,  0.4822, -0.2166, -0.3288,  0.2285, -0.2834])), ('2.weight', tensor([[-0.1623, -0.1526, -0.2662,  0.0235,  0.0949, -0.0439, -0.1812,  0.2690]])), ('2.bias', tensor([-0.1751]))])


In [19]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.1751], requires_grad=True)
tensor([-0.1751])


In [20]:
net[2].weight.grad is None

True

In [21]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(* [(name, param.shape) for name, param in net.named_parameters()]) # == state_dict()

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [ ]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)
net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]


In [22]:

def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 1)
        nn.init.zeros_(m.bias)
net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [23]:
def init_xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)

def init_42(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

# more parameter init way is in the link
# https://zh.d2l.ai/chapter_deep-learning-computation/parameters.html

tensor([ 0.0397, -0.6938, -0.1854, -0.0699])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])
